apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: nodejs-app29-run-pipeline
  namespace: demo-dev
# labels:
#     janus-idp.io/tekton: nodejs-app29
spec:
  params:
    - name: git-revision
      description: The git revision
      default: main
    - name: git-repo-url
      description: The repo url
    - name: output-image
      description: reference of the image that will get created
      default: image-registry.openshift-image-registry.svc:5000/rhdh/nodejs-app29
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        name: nodejs-app29-pipeline-$(uid)
      spec:
        params:
          - name: source-repo
            value: $(tt.params.git-repo-url)
          - name: source-branch
            value: $(tt.params.git-revision)
          - name: output-image
            value: $(tt.params.output-image)
        pipelineRef:
          name: nodejs-app29-pipeline
        # serviceAccountName: pipeline
        # timeout: 1h0m0s
        workspaces:
          - name: source-folder
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
